# Use an official Python runtime as a parent image
FROM public.ecr.aws/lambda/python:3.12

# Copy the requirements file into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run app.py when the container launches
CMD ["lambda_function.handler"]

CMD ["lambda_function.lambda_handler"]